### ISSUE TITLE
Cannot select multiple days for time input - User is forced add timings individually for each day

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#109]
![image](https://user-images.githubusercontent.com/35555935/39111163-c01d32a0-46f1-11e8-828b-23391188f5f6.png)

Say I have the same work schedule from Mon - Sat, I have to repeat same input for 5 rows? Need to same some solution to select days and add values all at once.

**Comment by mehadesai** [comment]
As discussed with Viraj, we have changed the checkbox to an icon.
As a general rule, when the user asks for repeat-data, we pick the last row that has completely filled data and repeat it across all half/full empty rows below it. Rows above it are unaffected.

Scenario 1 is correct.
Scenario 2, technically Sunday night shift is still considered as Sunday. So the first row for Mon-Tue will not get affected.
Scenario 3 is correct
Scenario 4 -> Thu/Fri/Sat/Sun data will be filled with the newly entered Wed data.
