### ISSUE TITLE
Sidebar (Menu) should have: dashboard, jobs (directory, add job), users

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#11]
![image](https://user-images.githubusercontent.com/35555935/37323945-ad89b326-26ac-11e8-99e0-bb81d88209c1.png)

**Comment by mehadesai** [comment]
The original idea was to have a nested nav bar
- Dashboard
- Jobs
-- Add a Job
-- List of Jobs
- Users
-- List of User
However, creating nested nav bars in ionic is an issue. 

Will re-open if required, later. 
For now, Admin only needs the following
- Dashboard
- Add Job
- List Jobs
