### ISSUE TITLE
Switch colors for text : Looks better when the background is red and text is white. 

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#127]
![image](https://user-images.githubusercontent.com/35555935/39288420-8049fa4a-4945-11e8-9ba3-537e8a84a3eb.png)

Change to :
![image](https://user-images.githubusercontent.com/35555935/39288438-95cbd352-4945-11e8-8984-dfd74d02d674.png)

**Comment by jeromie** [comment]
this is done. please check on server
