### ISSUE TITLE
Job cards - Posted X hours ago - Incorrect X value

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#152]
Customer:
![image](https://user-images.githubusercontent.com/35555935/39463071-61745330-4d33-11e8-8996-a79da2f01a1a.png)

Email
![image](https://user-images.githubusercontent.com/35555935/39463087-7d57774e-4d33-11e8-9474-7ae6d6672135.png)

**Comment by SavantMaithili** [comment]
@mehadesai , please confirm

- Value = date of approval (published date)
- Also, today I can make changes to published job; this should not affect the posted date on customer side.

**Comment by mehadesai** [comment]
Currently, we are using the job's created_at date.

You're right, we should be using the published_at date (or rather, the last updated_at timestamp). I don't think we're saving that. So even if we do want this change, it will be a big task and we may need to backfill values. It's too complicated.

Let's live with using created_at date for now.

**Comment by SavantMaithili** [comment]
Takes the last updated date
