### ISSUE TITLE
Approval flow :  'View Application' button displayed immediately on click of 'Approve' even before the success screen

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#153]
## Link to video

https://drive.google.com/open?id=13Ryl8xt6srFTIyyKKrV7InzEMAsx6Hp8

**Comment by SavantMaithili** [comment]
More on this video:

1. Image is actually rectangle shaped (see customer side or back end add jobs), while on this page i see an oval
2. If no benefits added at back end, grey out or disable may be
@mehadesai to revert on this

**Comment by SavantMaithili** [comment]
Reported issue is fixed.
However, assuming the following issue is related too:

Approve - Success screen - go back - button says 'Approve' for a second before it changes to 'View Application'.


Can we fix this?

**Comment by SavantMaithili** [comment]
@mehadesai the above commented? doesnt require fix?

**Comment by SavantMaithili** [comment]
Approve screen not loading - keeping this issue on hold

**Comment by tanvisalkar** [comment]
works now
