### ISSUE TITLE
New vs Seen Tag

### ISSUE THREAD

**Issue by mehadesai** [ajency/ProjectJ#165]
please push by post-lunch May 2nd.

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/39686515-177b8ace-51e7-11e8-9568-cf28163e80de.png)

**Comment by SavantMaithili** [comment]
Posted date issue persists, keeping this issue on hold; cannot test for now

**Comment by SavantMaithili** [comment]
Fails - Added new job - logged in with another user (*jobseeker) - New tag missing

View the same job - says seen
