### ISSUE TITLE
Hit back after successfully applying for job should grey out 'Apply' button

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#166]
Link to video
https://drive.google.com/open?id=1ItIDQ5yU5Uj79pEbks4hZXbUMV5T6df9

**Comment by SavantMaithili** [comment]
Please note: Apply should grey out not not show 'View application' , refer requirement doc, link below
https://docs.google.com/document/d/1Dtc8cWiYptxz1it-qRTHLpTcEi-GqKVw8I7_hoV_Vhg/edit#

**Comment by SavantMaithili** [comment]
If job has questionnaire set-
Click on Apply Now - Button grayed out + Loader till next page - Question 1 - hit back - Apply now to be enabled

**Comment by SavantMaithili** [comment]
Scenarios:

**When user applies for a job**

**If no question session:**

- Apply Now - button grayed out + Loader till success screen - Navigate back - Apply now button grayed out
- Apply Now - button grayed out + Loader till success screen - Navigate back to search page - Single page - Apply now button grayed out

**If question session exists:**

- Apply Now - button grayed out + Loader till next screen (Question1) - Navigate back - Apply now button enabled
- Apply Now - button grayed out + Loader till next screen (Question1)- Select answer - Hit Next - Loader +grey out - Question 2 screen - Navigate back - Next to be enabled - Hit Back - Apply now button enabled
- For last question - Hit Next on  Last question - Grey out + Loader - Success screen - Hit back - Apply button to be disabled

**Comment by mehadesai** [comment]
Suppose there are 100 jobs in the system and there are three users - 
1. User1 is job-seeker ONLY
2. User2 is job-owner ONLY (and owns 4 jobs)
3. User3 is job-seeker + job-owner (and owns 10 jobs)

These are the use cases we will encounter:
1. User1 will be able to apply to all 100 jobs.
a. He sees APPLY on all 100 jobs
b. When he clicks APPLY on any job, he completes the application flow (profile + application as the case may be) and when he goes back the apply button turns to grey.
c. When he comes back to this job at any point, the button will still be grey
d. Note: This will need to be updated slightly once we build the employer side app.

2. User2 owns 4 jobs.
a. For these 4 jobs, he sees “APPROVE”
b. When he clicks on APPROVE, he goes to a success screen. On coming back to the job, he sees VIEW APPLICATIONS
c. When he comes back to this job at any point, the button will say VIEW APPLICATIONS
d. For the remaining 96 jobs, he should NOT be allowed to see them.

3. User3 will be able to apply to 96 jobs
a. For these 96 jobs, flow will be same as (1) above
b. For the remaining 4 jobs, flow will be same as 2(a) + (b) + (c)

**Comment by SavantMaithili** [comment]
This is not fixed

**Comment by SavantMaithili** [comment]
@tanvisalkar 

Above issue was: if user is a job seeker only, he should never see the view application button

Tried to apply for a job to test above scenario and noticed that click on 'APPLY' shows disabled + loader for a while and then the button is enabled again, did not go to next page. 
Please refer below link to video file
https://drive.google.com/open?id=1tqa3tKTvqagD93-loNP-BMMXIfvfV6-Y

**Comment by SavantMaithili** [comment]
original issue is observed again: Apply job - navigate back - apply now not grayed out (for jobseeker)

**Comment by SavantMaithili** [comment]
Issues above resolved
