### ISSUE TITLE
Admin - Filter on Sub industry only shows records in 'Draft' status

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#169]
@verlekar-viraj As dicussed

**Comment by SavantMaithili** [comment]
@mehadesai - We have same sub industry names for multiple industries; 

**eg:** 

- Airport - Cleaner/Washer
- Corporate - Cleaner/Washer

In list of jobs (admin); we dont have Industry filter; both these sub industries are listed in sub-industry filter (cannot relate to this); need to either add industry column to list, or suggest some workaround

**Comment by mehadesai** [comment]
1. Dropdown of sub-industries should have unique, alphabetical list of sub-industries.
2. Include industries in list view (along with company name and phone number, as previously discussed/raised)
3. On desktop, move status column next to designation/job role.
4. On mobile, use a view as explained in the attached screenshot. We can move to a title + value approach for each block if required.

**Comment by verlekar-viraj** [comment]
Only Mobile view UI is pending with @jeromie

**Comment by SavantMaithili** [comment]
Need to check on mobile, desktop is fine
