### ISSUE TITLE
Horizontal job cards issues

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#175]
- 5 jobs load as of now, but reload happens after swiping 3rd itself
-   Search page - horizontal jobs slider - maps - search using filter - **hides some job markers**. say user sets filter criteria as only salary may be 0 - 75. It will shows all jobs in database with this salary range - larger map area (entire hong kong in real time) is covered and jobs are hidden 
- and then when i slide backwards - zoom level is so much that i see only 1 job in the center of the map, assuming when the second page is loaded , the map zoom level changes as per job availability in that area. And this new zoom level is set when user swipes to previous jobs too and hence the different zoom level. [in below attched we have only 1 job in the second page load]

https://drive.google.com/open?id=1OJX8pUW4x2XwXMN5OaeIe2BuP3l1Yujt

@mehadesai need your inputs

**Comment by tanvisalkar** [comment]
Ignore for now

**Comment by SavantMaithili** [comment]
We can keep this open

**Comment by SavantMaithili** [comment]
Closing for now with known issue
Search page - horizontal jobs slider - maps - search using filter - hides some job markers. say user sets filter criteria as only salary may be 0 - 75. It will shows all jobs in database with this salary range - larger map area (entire hong kong in real time) is covered and jobs are hidden
