### ISSUE TITLE
Revisiting the search page with filters applied previously hides the 'Show Results' button

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#176]

**Comment by SavantMaithili** [comment]
**Before filters applied**
![image](https://user-images.githubusercontent.com/35555935/39690799-f34ef28c-51f8-11e8-8f7c-ead963c9be1b.png)

**Apply filters - show results - revisit the filters page**

![image](https://user-images.githubusercontent.com/35555935/39691004-ad04b428-51f9-11e8-8922-f8e22b1ee824.png)


**Reset filters**
![image](https://user-images.githubusercontent.com/35555935/39690934-66f09830-51f9-11e8-9a5d-549ab81831ec.png)

**Comment by jeromie** [comment]
@sujitgawas19 are you doing a show/hide of the tab bar for some condition?

**Comment by sujitgawas19** [comment]
@jeromie Nope. It was because of change in navigation method. I have fixed it.
