### ISSUE TITLE
Language settings is reset when user navigates to Single Job View

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#179]
- Change in language settings to Cantonese 
- Check all pages - shows Cantonese 
- Single job view - English
- Going  back to any page after visiting the Single job view resets the language settings

## Storage issue as per discussion with @verlekar-viraj

**Comment by mehadesai** [comment]
this should get fixed with viraj's changes from today. assigning to QA so that you can mark it as closed after you've tested viraj's stuff.
