### ISSUE TITLE
Admin: Workplace Address to use Google Maps API

### ISSUE THREAD

**Issue by mehadesai** [ajency/ProjectJ#181]
1. Remove lat-long fields visible on UI. 
2. User types in address. On blur (event), call the maps API and plot this address on maps.
3. User should be able to move the marker, if it is incorrect. On moving the marker, the address will also change accordingly.
4. When he hits save, the lat-long for this address will get saved, along with the address.

Ref: https://github.com/ajency/fnbcircle/blob/master/public/js/maps.js

**Comment by SavantMaithili** [comment]
- Type job location - Marker plotted - user can manually change ,marker position on map - address changes accordingly on clicking address text area
  - User may type in address and not select from drop down - Lat-long will go blank - Validation required may be?

**Comment by SavantMaithili** [comment]
Keeping it open for now
