### ISSUE TITLE
Back button on profile page

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#186]
![image](https://user-images.githubusercontent.com/35555935/39859165-7ef2ec8a-5456-11e8-9dff-f301b3243387.png)

**Comment by jeromie** [comment]
can you list the steps to reproduce this?

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/39913823-d05d86dc-5520-11e8-8d28-a42d23a08820.png)

Not sure when this happens, any page that takes too long to load comes with this
