### ISSUE TITLE
Incorrect otp error

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#196]
1. Change language to Chinese in account settings
2. Log out
3. Login again (preferably with another device)
4. By default shows in English the on boarding screen
5. Enter phone number + verification code
6. shows incorrect OTP error and changes screen to Chinese language

https://drive.google.com/open?id=1Sg9WIrMqPiZmfNv4bx30najR8uioEUVC

**Comment by verlekar-viraj** [comment]
Language switches that means login happened. Probably throwing some different error after login. Since it is common catch, shows incorrect OTP. Issue is same like wrong number. Will check.

**Comment by SavantMaithili** [comment]
The code (code means something like 'auth/network-request-failed') goes null - Error displayed is insufficient storage
Message to show: "Something went wrong. Please click RESEND SMS."
Code goes thru - matches either incorrect verification code OR Expired - Respective messages
No changes needed here, I guess.
Code goes through but does not match either in point 2, - shows insufficient storage
Message to show: "Something went wrong. Please click RESEND SMS."
