### ISSUE TITLE
Check box to the left, value to the right

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#2]
![image](https://user-images.githubusercontent.com/35555935/37322871-2a7b03dc-26a6-11e8-936b-a3343869c96f.png)

![image](https://user-images.githubusercontent.com/35555935/37322889-4a111830-26a6-11e8-95f9-e7bf000eccd0.png)

**Comment by jeromie** [comment]
@tanvisalkar can you use ion-checkbox that was in the original ui instead of input type checkbox? This will position the checkbox properly.
