### ISSUE TITLE
Questionnaire related issues

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#216]
Please see link to video below

https://drive.google.com/open?id=1zu2a-fFgUAQPhaJ64r2I4We3peMLZgUr

**Comment by mehadesai** [comment]
Two things happening here:
1. the "next" button takes forever on the second question because that is why the "apply" is actually happening. If it takes about 4-5 seconds, I think that's okay. Ideally, it should be far less.
2. The other options should become non-selectable once he has hit next.

**Comment by tanvisalkar** [comment]
1. applyjob api takes 618ms.. find attached screenshot.
![screen shot 2018-05-22 at 12 54 07 pm](https://user-images.githubusercontent.com/26565683/40347862-69d975d6-5dbf-11e8-89f4-02eb28c2eadc.png)
2. DONE
