### ISSUE TITLE
Filters to be besides respective columns

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#22]
![image](https://user-images.githubusercontent.com/35555935/37578806-eff156d0-2b32-11e8-85e1-10dcb5d51a45.png)

### 
Like this:
![image](https://user-images.githubusercontent.com/35555935/37578845-1665cc9c-2b33-11e8-92fb-662a734c94a1.png)

**Comment by SavantMaithili** [comment]
Also, remove "Apply button", there is no way in this design to close the drop down, remains on the screen until user manually reloads the page
![image](https://user-images.githubusercontent.com/35555935/37578911-862677d8-2b61-11e8-83e3-0fac13206c25.png)

**Comment by mehadesai** [comment]
This view will not work for mobile. The dropdowns have now been implemented to close on click of Apply/Reset and the select dropdown itself. This should be okay for now.
