### ISSUE TITLE
Blank screens for ‘no saved jobs’ and ‘no conversations’

### ISSUE THREAD

**Issue by mehadesai** [ajency/ProjectJ#223]
[ No conversations found.pdf](https://github.com/ajency/ProjectJ/files/2021706/No.conversations.found.pdf)

[No saved jobs.pdf](https://github.com/ajency/ProjectJ/files/2021710/No.saved.jobs.pdf)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/40307865-bf43dbae-5d21-11e8-9b01-b83f79081610.png)
