### ISSUE TITLE
Dark grey strip visible at the top left corner on several pages

### ISSUE THREAD

**Issue by mehadesai** [ajency/ProjectJ#226]

**Comment by jeromie** [comment]
@mehadesai which pages?

**Comment by mehadesai** [comment]
Search and Address were the two places pointed out by Hugo and Maithili respectively. I can't see it in either of the places now (I've attached some older screenshots). Plus, I also do see an email that mentions that you'd pushed this to develop a week ago. It showed up on my open items and I could not find it on exitsing github issues either, so created a new issue. Closing this for now. 
![unnamed](https://user-images.githubusercontent.com/7439293/40368039-709c671e-5df8-11e8-93df-678fe011f86e.jpg)
![unnamed](https://user-images.githubusercontent.com/7439293/40368040-70ce2a88-5df8-11e8-9fd7-f3fb08f30696.png)
