### ISSUE TITLE
APIs on https://pro-j.app not working

### ISSUE THREAD

**Issue by mehadesai** [ajency/ProjectJ#227]
https://pro-j.app now points to https://project-j-main.firebaseapp.com. However, pro-j.app does not load many of the APIs. Can we see what is going wrong here?

**Comment by verlekar-viraj** [comment]
@AJ-Shank, issue is same as localhost was not allowed on dev. You'll have to do the same changes for main too.

Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://project-j-main.firebaseapp.com' that is not equal to the supplied origin. Origin 'https://pro-j.app' is therefore not allowed access.
