### ISSUE TITLE
Upload logo - Not saving the image, says no file chosen

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#24]
![image](https://user-images.githubusercontent.com/35555935/37579980-493de558-2b67-11e8-8c77-2297557a54d3.png)

**Comment by SavantMaithili** [comment]
Upload logo removed
![image](https://user-images.githubusercontent.com/35555935/37767198-40ddb12e-2def-11e8-9ad6-021245898892.png)

**Comment by verlekar-viraj** [comment]
Upload logo will be seen on edit mode or if saved once - tanvi

**Comment by SavantMaithili** [comment]
https://github.com/ajency/ProjectJ/issues/43
