### ISSUE TITLE
Job summary page

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#35]
May be we can show some icons to say the values are address, salary, etc, currently cannot distinguish anything

![image](https://user-images.githubusercontent.com/35555935/37640324-0d7f1382-2c3b-11e8-93f5-fa82fdbb1084.png)

**Comment by mehadesai** [comment]
Icons still need to be provided by client. He has given dummy icons for now.
Plus, we have moved onto a different kind of view for single job now.
Closing this ticket because it is not relevant anymore.
