### ISSUE TITLE
Hide the recaptcha and make the confirmation in line with the screen (not as a pop up)

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#42]
![image](https://user-images.githubusercontent.com/35555935/37706227-bcefcbc4-2d24-11e8-9291-fe3e27fa7771.png)

**Comment by verlekar-viraj** [comment]
Waiting for designs from client. Will be changed after that

**Comment by mehadesai** [comment]
This has been redesigned. Closing.
