### ISSUE TITLE
Validation error for questions to be displayed on;y when action button is hit

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#46]
Steps:

- Enter few fields.
- Hit Save
- Now select "YES" for questions.
- Validation error is displayed

![image](https://user-images.githubusercontent.com/35555935/37706625-391515c8-2d26-11e8-814b-fd5ac6cde922.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/37769514-3e30acda-2df7-11e8-8558-e61d2d8cd46f.png)

**Comment by SavantMaithili** [comment]
Add Jobs - Enter email - validation error even before you click the Save button

**Comment by mehadesai** [comment]
fixed
