### ISSUE TITLE
On boarding Slider Scroll UI issue

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#47]
Office Iphone
![image](https://user-images.githubusercontent.com/35555935/37758222-6c5bd296-2dd5-11e8-88e3-51a33d94c051.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/38231406-168f43d4-3730-11e8-9979-90e8c91301bc.png)

**Comment by mehadesai** [comment]
Fixed in all cases expect very large screens... where there is a large gap between slider dots and image.
