### ISSUE TITLE
Additional validations for company name

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#91]
![image](https://user-images.githubusercontent.com/35555935/38719698-e1837186-3f10-11e8-908a-4ca00e692773.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/38794797-e34e25c8-4173-11e8-9dde-158f4529ed33.png)

**Comment by mehadesai** [comment]
Allow the following:
numbers
hyphen(-) e.g.: Peek-a-Boo patterns
and (&) e.g.: Sriram & Sons
comma(,)
dot (.) e.g.: ABC Farms Pvt. Ltd.

**Comment by SavantMaithili** [comment]
Allow '
Eg: Mc Donald's
