### ISSUE TITLE
Text Input fields should not be saved with only spaces

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/ProjectJ#94]
![image](https://user-images.githubusercontent.com/35555935/38720418-d53ae820-3f13-11e8-8788-63b673443938.png)

**Comment by SavantMaithili** [comment]
Same for More about this role and any text input fields

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/38720564-53fc923a-3f14-11e8-9092-76c37c75d693.png)

**Comment by mehadesai** [comment]
@verlekar-viraj to put in a check to remove spaces (if only spaces have been entered in a text field) when the user moves out of the field. No extra errors to be shown.

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/38794858-13babee2-4174-11e8-8742-491c6fed8fd7.png)
