### ISSUE TITLE
Incorrect error for "contact via"

### ISSUE THREAD

**Issue by mehadesai** [ajency/ProjectJ#95]
1. Error message shows up on Save. This is not mandatory until we submit for approval.
2.Error message is incorrect.
![screen shot 2018-04-13 at 12 17 00 pm](https://user-images.githubusercontent.com/7439293/38720660-bb53ba1c-3f14-11e8-8d01-ca864db13044.png)

**Comment by SavantMaithili** [comment]
not mandatory any more, no error
